### ISSUE TITLE
请教一个关于AES的ECB解密的问题

### ISSUE THREAD

**Issue by shanlanCoding** [BennyThink/yyets-restorer#1]
我有一个bat批处理，它的功能是下载某网站的视频，视频有加密，该脚本是调用OpenSSL命令进行解密。解密命令如下：
```
openssl aes-128-ecb -d -in "被加密的视频文件路径" -out "解密后的视频文件输出路径" -K key字符串
上面这行命令的意思是：调用OpenSSL，-d 解密；-in 输入文件的路径；-out 输出文件的路径； -K 密钥  
```

----
通过BAT批处理调用这行命令能解密成功顺利播放，但是当我使用python代码尝试实现这个效果的时候，发现视频解密后无法播放，也就是没有解密成功，python实现这个功能的代码如下：
```python
        crypt = AES.new(key.encode("utf-8"), AES.MODE_ECB)
        plain_text = crypt.decrypt(data) #data是视频的二进制流
        return plain_text.rstrip(b'\0')
```
但是我发现您的代码是这样写的：
```python
  def decrypt(data, key):
      cipher = Cipher(algorithms.AES(key), modes.ECB(), backend=default_backend())
      decryptor = cipher.decryptor()
      return decryptor.update(data) + decryptor.finalize()
```
其实我不太理解您的这个`Cipher(algorithms.AES(key), modes.ECB(), backend=default_backend())`写法，您看看我需要如何改进代码？

**Comment by BennyThink** [comment]
这个是从cryptography 官网复制过来的。猜测你用的是pycrypto吧。

**Comment by shanlanCoding** [comment]
> 这个是从cryptography 官网复制过来的。猜测你用的是pycrypto吧。

目前导包的是`from Crypto.Cipher import AES`

**Comment by BennyThink** [comment]
1. pycrypto已经六七年不更新了
2. 最后 `rstrip(b'\0')`干什么呢，得到plaintext之后应该rb模式写文件呀。

**Comment by shanlanCoding** [comment]
> 1. pycrypto已经六七年不更新了
> 2. 最后 `rstrip(b'\0')`干什么呢，得到plaintext之后应该rb模式写文件呀。

1. 现在应该用什么库来进行AES解密？cryptography 吗？
2. `\0`是字符串的结束符号。所以这行的意思是删除字符串的结束符，不过这段代码是抄的。至于回写数据到硬盘，不是在这个函数里操作。

**Comment by BennyThink** [comment]
1. Yes
2. 🤔奇怪，应该直接写？要不你试试cryptography? 示例代码你都有啦。
